spring:
  application:
    name: orchestrator
  profiles:
    default: dev
    group:
        dev:
          - logging
          - spring-docs
          - demo
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, refresh
  endpoint:
    shutdown:
      enabled: true
    startup:
      enabled: true

server:
  port: 9001

services:
  jarPath: "/jars"
  server:
    all:
      name: "All Server222222"
      port: 1000
    tas:
      name: "TAS"
      port: 8090
      file: "did-tas-server-1.0.0.jar"
    issuer:
      name: "Issuer"
      port: 8091
      file: "did-issuer-server-1.0.0.jar"
    verifier:
      name: "Verifier"
      port: 8092
      file: "did-verifier-server-1.0.0.jar"
    api:
      name: "API-Gateway"
      port: 8093
      file: "did-api-server-1.0.0.jar"
    cas:
      name: "CAS"
      port: 8094
      file: "did-cas-server-1.0.0.jar"
    wallet:
      name: "WalletService"
      port: 8095
      file: "did-wallet-server-1.0.0.jar"
    demo:
      name: "DEMO"
      port: 8099
      file: "did-demo-server-1.0.0.jar"
    orchestrator:
      name: "Orchestrator"
      port: 9001
    TEST:
      name: "test"
      port: 10000     
